// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3ndqTZOWUyCxZf7IXW_PJHcQSx4oCRQ',
    appId: '1:1063297145500:web:29e4dde8ba90824e6c2b59',
    messagingSenderId: '1063297145500',
    projectId: 'investify-1d3ba',
    authDomain: 'investify-1d3ba.firebaseapp.com',
    storageBucket: 'investify-1d3ba.firebasestorage.app',
    measurementId: 'G-9Q9TMDEEHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtJ5XGx9FnJb2l7Z5W_YjBeelGDqJGgg',
    appId: '1:1063297145500:android:9df9ca33ecd4a0986c2b59',
    messagingSenderId: '1063297145500',
    projectId: 'investify-1d3ba',
    storageBucket: 'investify-1d3ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwn8sftYjJFUvinVvMSSpPU_f0noEAaU',
    appId: '1:1063297145500:ios:0d4ac9cca7d9ffe36c2b59',
    messagingSenderId: '1063297145500',
    projectId: 'investify-1d3ba',
    storageBucket: 'investify-1d3ba.firebasestorage.app',
    iosBundleId: 'com.example.investapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwn8sftYjJFUvinVvMSSpPU_f0noEAaU',
    appId: '1:1063297145500:ios:0d4ac9cca7d9ffe36c2b59',
    messagingSenderId: '1063297145500',
    projectId: 'investify-1d3ba',
    storageBucket: 'investify-1d3ba.firebasestorage.app',
    iosBundleId: 'com.example.investapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG3ndqTZOWUyCxZf7IXW_PJHcQSx4oCRQ',
    appId: '1:1063297145500:web:365fe679b451e31e6c2b59',
    messagingSenderId: '1063297145500',
    projectId: 'investify-1d3ba',
    authDomain: 'investify-1d3ba.firebaseapp.com',
    storageBucket: 'investify-1d3ba.firebasestorage.app',
    measurementId: 'G-NXGTLYHXPT',
  );
}
